"""create name space

Revision ID: 9ce4a5e45a4b
Revises: f8015970d8e4
Create Date: 2026-05-15 19:53:22.239818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce4a5e45a4b'
down_revision: Union[str, Sequence[str], None] = 'f8015970d8e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('name', sa.String(), nullable=True))
    op.create_index(op.f('ix_songs_name'), 'songs', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_songs_name'), table_name='songs')
    op.drop_column('songs', 'name')
    # ### end Alembic commands ###
