""" update models

Revision ID: c5044fd8d9fd
Revises: 9ce4a5e45a4b
Create Date: 2026-05-15 20:23:29.074393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5044fd8d9fd'
down_revision: Union[str, Sequence[str], None] = '9ce4a5e45a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('song_artist', 'song_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('song_artist', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_song_artist_artist_id'), table_name='song_artist')
    op.drop_index(op.f('ix_song_artist_song_id'), table_name='song_artist')
    op.create_foreign_key(None, 'song_artist', 'artists', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'song_artist', 'songs', ['song_id'], ['id'])
    op.alter_column('songs', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('songs', 'file_lyric',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs', 'file_lyric',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('songs', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'song_artist', type_='foreignkey')
    op.drop_constraint(None, 'song_artist', type_='foreignkey')
    op.create_index(op.f('ix_song_artist_song_id'), 'song_artist', ['song_id'], unique=False)
    op.create_index(op.f('ix_song_artist_artist_id'), 'song_artist', ['artist_id'], unique=False)
    op.alter_column('song_artist', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('song_artist', 'song_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artists', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
