"""artist, lyrics and relationship are created

Revision ID: e8a441b136c8
Revises: 
Create Date: 2026-05-15 18:08:04.745208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8a441b136c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artists_id'), 'artists', ['id'], unique=False)
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=False)
    op.create_table('lyric_artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lyric_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lyric_artist_artist_id'), 'lyric_artist', ['artist_id'], unique=False)
    op.create_index(op.f('ix_lyric_artist_id'), 'lyric_artist', ['id'], unique=False)
    op.create_index(op.f('ix_lyric_artist_lyric_id'), 'lyric_artist', ['lyric_id'], unique=False)
    op.create_table('lyrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lyrics_content'), 'lyrics', ['content'], unique=False)
    op.create_index(op.f('ix_lyrics_id'), 'lyrics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lyrics_id'), table_name='lyrics')
    op.drop_index(op.f('ix_lyrics_content'), table_name='lyrics')
    op.drop_table('lyrics')
    op.drop_index(op.f('ix_lyric_artist_lyric_id'), table_name='lyric_artist')
    op.drop_index(op.f('ix_lyric_artist_id'), table_name='lyric_artist')
    op.drop_index(op.f('ix_lyric_artist_artist_id'), table_name='lyric_artist')
    op.drop_table('lyric_artist')
    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.drop_index(op.f('ix_artists_id'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
