"""change name tables

Revision ID: f8015970d8e4
Revises: e8a441b136c8
Create Date: 2026-05-15 19:16:12.766497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8015970d8e4'
down_revision: Union[str, Sequence[str], None] = 'e8a441b136c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song_artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_song_artist_artist_id'), 'song_artist', ['artist_id'], unique=False)
    op.create_index(op.f('ix_song_artist_id'), 'song_artist', ['id'], unique=False)
    op.create_index(op.f('ix_song_artist_song_id'), 'song_artist', ['song_id'], unique=False)
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_seq', sa.String(), nullable=True),
    sa.Column('file_lyric', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_songs_file_lyric'), 'songs', ['file_lyric'], unique=False)
    op.create_index(op.f('ix_songs_file_seq'), 'songs', ['file_seq'], unique=False)
    op.create_index(op.f('ix_songs_id'), 'songs', ['id'], unique=False)
    op.drop_index(op.f('ix_lyric_artist_artist_id'), table_name='lyric_artist')
    op.drop_index(op.f('ix_lyric_artist_id'), table_name='lyric_artist')
    op.drop_index(op.f('ix_lyric_artist_lyric_id'), table_name='lyric_artist')
    op.drop_table('lyric_artist')
    op.drop_index(op.f('ix_lyrics_content'), table_name='lyrics')
    op.drop_index(op.f('ix_lyrics_id'), table_name='lyrics')
    op.drop_table('lyrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lyrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('lyrics_pkey'))
    )
    op.create_index(op.f('ix_lyrics_id'), 'lyrics', ['id'], unique=False)
    op.create_index(op.f('ix_lyrics_content'), 'lyrics', ['content'], unique=False)
    op.create_table('lyric_artist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lyric_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('lyric_artist_pkey'))
    )
    op.create_index(op.f('ix_lyric_artist_lyric_id'), 'lyric_artist', ['lyric_id'], unique=False)
    op.create_index(op.f('ix_lyric_artist_id'), 'lyric_artist', ['id'], unique=False)
    op.create_index(op.f('ix_lyric_artist_artist_id'), 'lyric_artist', ['artist_id'], unique=False)
    op.drop_index(op.f('ix_songs_id'), table_name='songs')
    op.drop_index(op.f('ix_songs_file_seq'), table_name='songs')
    op.drop_index(op.f('ix_songs_file_lyric'), table_name='songs')
    op.drop_table('songs')
    op.drop_index(op.f('ix_song_artist_song_id'), table_name='song_artist')
    op.drop_index(op.f('ix_song_artist_id'), table_name='song_artist')
    op.drop_index(op.f('ix_song_artist_artist_id'), table_name='song_artist')
    op.drop_table('song_artist')
    # ### end Alembic commands ###
